#!/bin/bash
#
# [PG-Blitz]
#
# GitHub:   https://github.com/Admin9705/PlexGuide.com-The-Awesome-Plex-Server
# Author:   Admin9705
# URL:      https://plexguide.com
#
# PlexGuide Copyright (C) 2018 PlexGuide.com
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    - pause:
        prompt: "\nType the Exact Path of the Folder/HD\n\nExample 1: /secondhd/shows\nExample 2: /thirdhd/media\nExample 3: /sparedrive/media/downloads\n\nWARNING: Start with a Trailing Slash | No Trailing Slash at the End\n\nThen PRESS [ENTER]"
      register: pathinput

    - name: Check if the Path Exists
      stat:
        path: "{{pathinput.user_input}}"
      register: path

    - debug: msg="Does the Path Exist? {{path.stat.exists}}"

    - pause:
        prompt: "\nFAILED! Path - {{pathinput.user_input}} does not exist!\n\nTIP 1: Test by Typing > ls -la {{pathinput.user_input}}\nTIP 2: If a NAS, conduct research prior!\nTIP 3: PG does not mount your drives! You have to setup prior!\nTIP 4: Start with a Trailing Slash | No Trailing Slash at the End\n\nPress [ENTER] to Continue"
      when: path.stat.exists == False

    - fail:
        msg: "Failed Warning: Path - {{pathinput.user_input}} - DOES NOT EXIST!"
      when: path.stat.exists == False

    - pause:
        prompt: "\nPath - {{pathinput.user_input}} exists!\nPress [ENTER] to Continue"
      when: path.stat.exists == True

    - name: Call Up Last Number Variable
      shell: "cat /var/plexguide/multi.filler"
      register: count

    - name: Convert unit
      set_fact:
        countplus: "{{count.stdout}}"

    - debug: msg="Count Up - {{countplus}}"

    - name: Set New Count
      shell: "echo {{countplus}} > /var/plexguide/multi.count"

    - name: Store Information
      shell: "echo {{pathinput.user_input}} > /opt/appdata/plexguide/multi/{{countplus}}"
